<?php

declare(strict_types=1);

/**
 * @class 验证类
 * @auth echo
 * @email 945462788@qq.com
 * @github https://github.com/945462788
 **/


namespace app\controller1\api;
use app\common\model\user\UserModel;
use app\common\service\AuthService;
use app\common\service\utils\TokenService;
use app\common\service\wechat\WeChatMiniProgramService;
use app\common\service\wechat\WeChatService;

class Auth extends ApiBase
{
    protected function initialize():void
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->service = app()->make(AuthService::class);
    }

    /**
     * 微信小程序登陆
     */
    public function weChatAppLogin():void
    {
        [$code,$cache_key] = param_list(['code',null],['cache_key',null]);

        $miniProgramService = app()->make(WeChatMiniProgramService::class);

        $sessionKey = cache('wx_app_user_session_'.$cache_key);

        if (!$code) app('response')->fail('缺少code参数',[],40002);

        if ($code && !$sessionKey)
        {
            $userInfo = $miniProgramService->login($code);

            $sessionKey = $userInfo['session_key'];

            $cache_key = md5($code);

            cache('wx_app_user_session_'.$code,$sessionKey,86400);
        }

        [$iv,$encryptedData] = param_list(['iv',''],['encryptedData','']);

        $userInfo = $miniProgramService->decryptData($sessionKey,$iv,$encryptedData);

        $userModel = app()->make(UserModel::class);

        if ($uid = $userModel->saveWeChatAppUser($userInfo))
        {
            $token = TokenService::instance()->create($uid);

            app('response')->success(compact('token','cache_key'));
        }

        app('response')->fail('微信小程序登录失败，请稍后重试');
    }

    /**
     * 微信登录
     */
    public function weChatLogin()
    {
        [$code,$state] = param_list(['code',''],['state','']);

        $wechatService = app()->make(WeChatService::class);

        if ($code)
        {
            $user_info = $wechatService->login();

            $userModel = app()->make(UserModel::class);

            if ($uid = $userModel->saveWeChatUser($user_info))
            {
                $token = TokenService::instance()->create($uid);

                app('response')->success(compact('token'));
            }

            app('response')->fail('微信登录失败，请稍后重试');
        }

        return $wechatService->redirect('http://base.echo.cysky.cc/wechat/login');

    }
}