<?php

declare(strict_types=1);

/**
 * @class 验证类
 * @auth echo
 * @email 945462788@qq.com
 * @github https://github.com/945462788
 **/


namespace app\controller\api;
use app\common\model\user\UserModel;
use app\common\service\AuthService;
use app\common\service\system\TokenService;
use app\common\service\user\UserService;
use app\common\service\wechat\WeChatMiniProgramService;

class Auth extends ApiBase
{
    protected function initialize():void
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->service = app()->make(AuthService::class);
    }

    /**
     * 微信小程序登陆
     */
    public function weChatAppLogin():void
    {
        $code = $this->request->param('code',null);

        $miniProgramService = app()->make(WeChatMiniProgramService::class);

        $session_key = cache('wx_app_user_session_'.$code);

        if ($code && !$session_key)
        {
            $user_info = $miniProgramService->login($code);

            $session_key = $user_info['session_key'];

            cache('wx_app_user_session_'.$code,$session_key,86400);
        }

        [$iv,$encryptedData] = param_list(['iv',''],['encryptedData','']);

        $user_info = $miniProgramService->decryptData($session_key,$iv,$encryptedData);

        $userModel = app()->make(UserModel::class);

        if ($uid =$userModel->saveWeChatAppUser($user_info))
        {
            $token = TokenService::instance()->create($uid);

            app('response')->success(compact('token','session_key'));
        }

        app('response')->fail('添加用户失败，请稍后重试');
    }

    /**
     * 微信登录
     */
    public function weChatLogin():void
    {
        $code = $this->request->param('code');


    }
}