<?php

declare(strict_types=1);

/**
 * @class
 * @author echo
 * @email 945462788@qq.com
 * @github https://github.com/945462788
 **/


namespace app\controller1\api\user;


use app\BaseController;
use app\common\service\user\UserService;

class User extends BaseController
{
    protected $service;

    protected function initialize():void
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->service = app()->make(UserService::class);
    }

    /**
     * @return void
     */
    public function getUserInfo():void
    {
        $user_info = $this->service->userIdByUser($this->request->user_id);

        $user_info->hidden(['user_id','wechat_open_id','unionid','password','last_login_time','create_time','status']);

        app('response')->success($user_info);
    }
}