<?php

declare(strict_types=1);

/**
 * @class
 * @author echo
 * @email 945462788@qq.com
 * @github https://github.com/945462788
 **/


namespace app\backup\controller\user;

use app\backup\controller\Base;
use app\backup\service\user\UserService;

class User extends Base
{
    protected $service;

    protected function initialize():void
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->service = app()->make(UserService::class);
    }

    /**
     * @return void
     */
    public function getUserInfo():void
    {
        $userInfo = $this->service->userIdByUser($this->request->user_id);

        $userInfo->hidden(['user_id','wechat_open_id','unionid','password','last_login_time','create_time','status','username','role_id']);

        app('response')->success($userInfo);
    }

    public function getShareQrCode()
    {
        $userInfo = $this->service->userIdByUser($this->request->user_id);

        app('response')->success('ok',$this->service->setModel($userInfo)->getShareQrcode());
    }
}